name: rekovi_mobile
description: Aplicativo híbrido (Flutter) idêntico à versão web/mobile do Rekovi
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.5.6
  http: ^1.2.2
  url_launcher: ^6.3.0
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  webview_flutter: ^4.10.0
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  mime: ^1.0.5
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

