create table public.pre_approved_users (
  id bigint generated by default as identity not null,
  email text not null,
  permission_type text not null,
  created_at timestamp with time zone null default now(),
  status text not null default 'active'::text,
  empresa text null,
  ultimo_login timestamp with time zone null,
  logs jsonb null default '[]'::jsonb,
  area_atuacao jsonb null,
  nome text null,
  constraint pre_approved_users_pkey primary key (id),
  constraint pre_approved_users_email_key unique (email)
) TABLESPACE pg_default;

create trigger on_user_change BEFORE INSERT
or
update on pre_approved_users for EACH row
execute FUNCTION log_user_changes ();